In [3]:
import pandas as pd
import matplotlib.pyplot as plt #导入图像库
from sklearn.cross_validation import train_test_split

In [4]:
def outlier_processing(df,col):
    s=df[col]
    oneQuoter=s.quantile(0.25)
    threeQuote=s.quantile(0.75)
    irq=threeQuote-oneQuoter
    min=oneQuoter-1.5*irq
    max=threeQuote+1.5*irq
    df=df[df[col]<=max]
    df=df[df[col]>=min]
    return df

In [10]:
data = pd.read_csv('MissingData2.csv')
data.describe()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,145563.000000,145563.000000,145563.000000,145563.000000,145563.000000,1.455630e+05,145563.000000,145563.000000,145563.000000,145563.000000,145563.000000
mean,0.067538,5.941378,52.110701,0.389185,334.548251,6.116310e+03,8.553788,0.231309,1.033346,0.205622,0.759863
std,0.250952,250.510835,14.567652,3.756944,1947.228209,1.318221e+04,5.141132,3.728803,1.133115,3.712455,1.116141
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.031218,41.000000,0.000000,0.173934,2.554000e+03,5.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.158817,52.000000,0.000000,0.359090,5.000000e+03,8.000000,0.000000,1.000000,0.000000,0.000000
75%,0.000000,0.561085,62.000000,0.000000,0.770641,8.166000e+03,11.000000,0.000000,2.000000,0.000000,1.000000
max,1.000000,50708.000000,107.000000,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000,20.000000

In [13]:
# 年龄等于0的异常值进行剔除
data = data[data['age'] > 0]
data = data[data['NumberOfTime30-59DaysPastDueNotWorse'] < 90]#剔除异常值
data.to_csv('MissingData3.csv')

In [15]:
data['SeriousDlqin2yrs']=1-data['SeriousDlqin2yrs']
data.to_csv('MissingData4.csv')

In [16]:
Y = data['SeriousDlqin2yrs']
X = data.ix[:, 1:]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)
print(Y_train)

70614     1
111700    0
15820     0
104383    0
136474    0
104204    0
118209    0
98848     0
91171     0
49958     0
33183     0
105492    1
55262     0
112064    0
139113    0
102857    0
139219    1
34144     0
72593     0
64797     0
87282     0
59293     0
138890    0
136356    0
114984    0
51405     0
136786    0
34343     1
138485    0
40053     0
         ..
119593    0
84795     0
122320    0
49895     0
132059    0
31975     0
108665    0
133761    0
73247     0
133136    0
84095     0
7886      0
70718     0
67804     1
138193    0
82585     0
101353    0
108792    0
17112     0
80308     0
52706     0
48682     0
112583    0
86425     0
122757    0
42063     0
97786     0
96085     0
118119    1
43641     0
Name: SeriousDlqin2yrs, Length: 101747, dtype: int64

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

In [17]:
train = pd.concat([Y_train, X_train], axis=1)
test = pd.concat([Y_test, X_test], axis=1)
clasTest = test.groupby('SeriousDlqin2yrs')['SeriousDlqin2yrs'].count()
train.to_csv('TrainData.csv',index=False)
test.to_csv('TestData.csv',index=False)

In [18]:
print(train.shape)
print(test.shape)

(101747, 11)
(43607, 11)